#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────────────
#  scripts/gdrive_setup.sh
#
#  One-time setup: installs rclone, authenticates with Google Drive,
#  creates the local watch folder, and registers the sync service.
#
#  Run once on the server:
#    chmod +x scripts/gdrive_setup.sh
#    ./scripts/gdrive_setup.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m'

PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SYNC_SCRIPT="$PROJECT_DIR/scripts/gdrive_sync.sh"
SERVICE_FILE="/etc/systemd/system/gdrive-sync.service"
ENV_FILE="$PROJECT_DIR/.env"

echo ""
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}  AI Clipper — Google Drive Setup${NC}"
echo -e "${BOLD}${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# ── Step 1: Install rclone ──────────────────────────────────────────────────
echo -e "${BOLD}Step 1 — Installing rclone${NC}"

if command -v rclone &>/dev/null; then
    echo -e "  ${GREEN}✓${NC} rclone already installed: $(rclone --version | head -1)"
else
    echo "  Downloading rclone..."
    curl -fsSL https://rclone.org/install.sh | sudo bash
    echo -e "  ${GREEN}✓${NC} rclone installed: $(rclone --version | head -1)"
fi

# ── Step 2: Configure Google Drive remote ─────────────────────────────────
echo ""
echo -e "${BOLD}Step 2 — Configure Google Drive${NC}"
echo ""

if rclone listremotes | grep -q "^gdrive:"; then
    echo -e "  ${GREEN}✓${NC} Google Drive remote 'gdrive' already configured."
    echo -e "  ${YELLOW}  To reconfigure, run: rclone config delete gdrive && run this script again${NC}"
else
    echo -e "  ${CYAN}This will open rclone's interactive config.${NC}"
    echo -e "  ${CYAN}When prompted:${NC}"
    echo -e "    ${BOLD}n${NC} → New remote"
    echo -e "    ${BOLD}gdrive${NC} → Name (type exactly this)"
    echo -e "    ${BOLD}drive${NC} → Storage type (Google Drive)"
    echo -e "    ${BOLD}Leave client_id blank${NC} (press Enter)"
    echo -e "    ${BOLD}Leave client_secret blank${NC} (press Enter)"
    echo -e "    ${BOLD}1${NC} → Full access scope"
    echo -e "    ${BOLD}n${NC} → No service account"
    echo -e "    ${BOLD}y${NC} → Use auto config (if on desktop) OR follow URL if on headless server"
    echo -e "    ${BOLD}n${NC} → Not a team drive (unless you're using a Shared Drive)"
    echo -e "    ${BOLD}y${NC} → Confirm and save"
    echo ""
    read -p "  Press Enter to open rclone config..."
    rclone config
fi

# ── Step 3: Get Google Drive folder path ──────────────────────────────────
echo ""
echo -e "${BOLD}Step 3 — Set Google Drive folder${NC}"
echo ""
echo -e "  ${CYAN}List your Google Drive folders:${NC}"
rclone lsd gdrive: 2>/dev/null | head -20 || echo "  (Could not list folders — check your rclone config)"
echo ""
read -p "  Enter the Google Drive folder name to watch (e.g. BrandBadePoster): " GDRIVE_FOLDER

if [ -z "$GDRIVE_FOLDER" ]; then
    echo -e "  ${RED}✗ No folder name entered. Exiting.${NC}"
    exit 1
fi

# Verify folder exists
if ! rclone lsd "gdrive:" 2>/dev/null | grep -q "$GDRIVE_FOLDER"; then
    echo -e "  ${YELLOW}⚠  Folder '$GDRIVE_FOLDER' not found in root. Creating it...${NC}"
    rclone mkdir "gdrive:$GDRIVE_FOLDER"
fi

GDRIVE_REMOTE="gdrive:$GDRIVE_FOLDER"
echo -e "  ${GREEN}✓${NC} Using Google Drive folder: $GDRIVE_REMOTE"

# ── Step 4: Set up local watch folder ─────────────────────────────────────
echo ""
echo -e "${BOLD}Step 4 — Local watch folder${NC}"

LOCAL_WATCH="$PROJECT_DIR/gdrive_inbox"
mkdir -p "$LOCAL_WATCH"
echo -e "  ${GREEN}✓${NC} Local folder: $LOCAL_WATCH"

# ── Step 5: Update .env ────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}Step 5 — Updating .env${NC}"

# Remove old WATCH_FOLDER and GDRIVE settings if present
if [ -f "$ENV_FILE" ]; then
    sed -i '/^WATCH_FOLDER=/d' "$ENV_FILE"
    sed -i '/^GDRIVE_REMOTE=/d' "$ENV_FILE"
    sed -i '/^GDRIVE_SYNC_INTERVAL=/d' "$ENV_FILE"
fi

cat >> "$ENV_FILE" << ENVEOF

# ── Google Drive Sync ──────────────────────────────────────────────────────
WATCH_FOLDER=$LOCAL_WATCH
GDRIVE_REMOTE=$GDRIVE_REMOTE
GDRIVE_SYNC_INTERVAL=30
ENVEOF

echo -e "  ${GREEN}✓${NC} .env updated"

# ── Step 6: Create sync script ─────────────────────────────────────────────
echo ""
echo -e "${BOLD}Step 6 — Creating sync script${NC}"

cat > "$SYNC_SCRIPT" << SYNCEOF
#!/usr/bin/env bash
# Auto-generated by gdrive_setup.sh
# Polls Google Drive and copies new videos to the local watch folder.
# ─────────────────────────────────────────────────────────────────────────────

source "$ENV_FILE" 2>/dev/null || true

REMOTE="\${GDRIVE_REMOTE:-$GDRIVE_REMOTE}"
LOCAL="\${WATCH_FOLDER:-$LOCAL_WATCH}"
INTERVAL="\${GDRIVE_SYNC_INTERVAL:-30}"
PROCESSED="$PROJECT_DIR/gdrive_processed"
LOG_FILE="$PROJECT_DIR/logs/gdrive_sync.log"

mkdir -p "\$LOCAL" "\$PROCESSED" "\$(dirname \$LOG_FILE)"

log() { echo "\$(date '+%Y-%m-%d %H:%M:%S') [GDrive] \$1" | tee -a "\$LOG_FILE"; }

log "Starting Google Drive sync loop"
log "Remote : \$REMOTE"
log "Local  : \$LOCAL"
log "Poll interval: \${INTERVAL}s"

while true; do
    # Copy new files from Drive → local (never delete from Drive)
    rclone copy \\
        "\$REMOTE" \\
        "\$LOCAL" \\
        --include "*.mp4" --include "*.mov" --include "*.avi" \\
        --include "*.mkv" --include "*.webm" \\
        --no-update-modtime \\
        --log-level INFO \\
        --log-file "\$LOG_FILE" \\
        2>&1

    # Move processed files from Drive to a /processed subfolder on Drive
    # so they don't get re-synced next time
    for f in "\$LOCAL"/*.{mp4,mov,avi,mkv,webm} 2>/dev/null; do
        [ -f "\$f" ] || continue
        fname="\$(basename \$f)"
        # Check if this file is still waiting (not yet picked up by watcher)
        # Watcher moves files to uploads/ so if it's still here it's waiting
        if [ -f "\$f" ]; then
            log "New video waiting: \$fname"
        fi
    done

    sleep "\$INTERVAL"
done
SYNCEOF

chmod +x "$SYNC_SCRIPT"
echo -e "  ${GREEN}✓${NC} Sync script created: $SYNC_SCRIPT"

# ── Step 7: Create systemd service ────────────────────────────────────────
echo ""
echo -e "${BOLD}Step 7 — Registering systemd service${NC}"

CURRENT_USER=$(whoami)

sudo tee "$SERVICE_FILE" > /dev/null << SVCEOF
[Unit]
Description=AI Clipper— Google Drive Sync
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$CURRENT_USER
WorkingDirectory=$PROJECT_DIR
ExecStart=$SYNC_SCRIPT
Restart=always
RestartSec=10
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
SVCEOF

sudo systemctl daemon-reload
sudo systemctl enable gdrive-sync
sudo systemctl start gdrive-sync

echo -e "  ${GREEN}✓${NC} Service 'gdrive-sync' enabled and started"

# ── Step 8: Restart main app ───────────────────────────────────────────────
echo ""
echo -e "${BOLD}Step 8 — Restarting Brand Bade Poster${NC}"

if sudo systemctl is-active --quiet posting; then
    sudo systemctl restart posting
    echo -e "  ${GREEN}✓${NC} App restarted — WATCH_FOLDER now points to Google Drive inbox"
else
    systemctl --user restart posting 2>/dev/null || true
    echo -e "  ${GREEN}✓${NC} App restarted"
fi

# ── Summary ────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}${GREEN}  Setup complete!${NC}"
echo -e "${BOLD}${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""
echo -e "  ${BOLD}Google Drive folder:${NC} $GDRIVE_REMOTE"
echo -e "  ${BOLD}Local watch folder: ${NC} $LOCAL_WATCH"
echo -e "  ${BOLD}Sync interval:      ${NC} every 30 seconds"
echo ""
echo -e "  ${CYAN}Workflow from now on:${NC}"
echo -e "  1. MrBade drops a video into ${BOLD}Google Drive → $GDRIVE_FOLDER${NC}"
echo -e "  2. Server detects it within 30 seconds"
echo -e "  3. Full pipeline runs automatically"
echo -e "  4. Clips appear in the dashboard for approval"
echo ""
echo -e "  ${CYAN}Useful commands:${NC}"
echo -e "  sudo journalctl -u gdrive-sync -f     # watch sync logs"
echo -e "  sudo systemctl status gdrive-sync      # check sync service"
echo -e "  cat logs/gdrive_sync.log               # full sync history"
echo ""
